[project]
name = "learning-machines-robobo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cbor2~=5.6",
    "coppeliasim-zmqremoteapi-client~=2.0",
    "gymnasium>=1.0.0",
    "numpy>1.24.4",
    "opencv-python>=4.10",
    "pyzmq~=26.0",
    "stable-baselines3[extra]>=2.4.1",
    "tensorboard>=2.14.0",
    "torch>=2.12.0",
    "torchvision>=0.27.0",
    "wandb>=0.19",
    "pandas>=2.2",
    "sb3-contrib>=2.9.0",
    "pytest>=9.1.0",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/rocm7.2"

[tool.pytest.ini_options]
testpaths = ["tests"]
